#!/usr/bin/env bash

if (( $# == 0 ))
then
    echo "Missing file parameter."
    echo "Usage: topc file"
    exit 1
elif (( $# > 1 ))
then
    echo "There exist more than one file paramter."
    echo "Usage: topc file"
    exit 1
fi
INPUT_FILE=$@
sed -E -e 's/ +\| +/\n/g' \
    -e 's/^(sudo|nohup) +//g' \
    -e 's/^ +//' \
    "$INPUT_FILE" \
    | cut -d' ' -f1 \
    | sed -E 's#.*/##' \
    | grep -vE '^(ll|ls|cd|echo|cat|vim)$' \
    | awk '{totCnt++; cmds[$1]++;} END{ for(cmd in cmds) {printf "%d %f %s\n", cmds[cmd], cmds[cmd]/totCnt*100, cmd;}}' \
    | sort -t' ' -k1,1nr -k3,3\
    | head -10\
    | awk '{printf "%4d %6.2f%%  %s\n", $1, $2, $3}'

